# Generated by Django 3.1.4 on 2020-12-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=128, verbose_name='Марка')),
                ('model', models.CharField(max_length=128, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('transmission', models.SmallIntegerField(choices=[(1, 'Механика'), (2, 'Автомат'), (3, 'Робот')], verbose_name='Коробка передач')),
                ('color', models.CharField(max_length=128, verbose_name='Цвет')),
            ],
        ),
    ]
